### ISSUE TITLE
Highcharts bower package

### ISSUE THREAD

**Issue by demogorgorn** [miloschuman/yii2-highcharts#13]
Hello! I have one small question - why don't you use the bower asset package of highcharts library in HighchartsAsset instead of distributing library files?

**Comment by miloschuman** [comment]
There are two main reasons thus far:

1. Yii2-highcharts is in fact a collection of 3 widgets: Highcharts, Highstock, and Highmaps. Each is packaged as a separate standalone JavaScript library from Highslide, but there is a lot of overlap between the included files in each library. Since any given view can have multiple charts, we have to prevent the same script from getting included from multiple sources (for instance `highcharts/exporting.js` and `highstock/exporting.js`).
2. To keep this widget light-weight, fast, and portable, it does not check your filesystem for the existence of asset files. To switch between debug (source) and production (minified) mode, I have to rely on the naming convention (*.js vs. *.src.js). Some files are not offered with both a minified and source version, so I create them at build time.

I know the situation is not ideal because it requires me to rebuild after every release, and I am open to the possibility as soon as it is workable.

**Comment by demogorgorn** [comment]
Ok! Thank you for a quick answer!
