### ISSUE TITLE
AJAH-loading chart

### ISSUE THREAD

**Issue by PT240R** [miloschuman/yii2-highcharts#22]
Hello. I've got an issue with your nice yii-hightcharts plugin.
When i load rendered chart via AJAH (rendered HTML instead XML), chart is not initializing because you appending javascript at bottom of page
```php
$this->view->registerJs($js, View::POS_READY, $key);
```
It runs once when DOM Loaded.
It would not work for HTML pieces loading dynamical (e.g. for chart widget).

Do you plan to change this behavior in future?

**Comment by antivir88** [comment]
Hi, ia'm detected bug on your extention:

\miloschuman\highcharts\HighchartsAsset::register($this) Register bundle on View !not_added_into_layout!

<?= \miloschuman\highcharts\Highcharts::widget([]); ?> Added js/css files into layout and rendering widget

Please move your code of "publish files" from widget() to register() !!!!

AJAX not working...

**Comment by antivir88** [comment]
public function init()
    {
        $this->sourcePath = __DIR__ . '/src/';
        $this->js = [
            YII_DEBUG ? 'js/jquery.multipleInput.js' : 'js/jquery.multipleInput.min.js'
        ];
        parent::init();
    }


it's sample

**Comment by miloschuman** [comment]
@PT240R This is the normal behavior for most widgets, including the official Yii widgets, such as ActiveForm. There are two ways to handle asynchronous loading of assets.

1. Use the [Pjax widget](http://www.yiiframework.com/doc-2.0/yii-widgets-pjax.html) widget.
2. In your controller, instead of using `$this->render('view')`, use `$this->renderAjax('view')`.

In both cases, it is best to assign a unique id to your chart so that it doesn't conflict with any existing widgets on the page.

**Comment by miloschuman** [comment]
@antivir88 I'm not sure that I understand you. If you are having the same problem, please refer to my previous response https://github.com/miloschuman/yii2-highcharts/issues/22#issuecomment-142637945. If you are having another issue, please open a separate issue so that I can address it individually.
