### ISSUE TITLE
Help with pie chart with result by sql

### ISSUE THREAD

**Issue by gugoan** [miloschuman/yii2-highcharts#35]
I am having difficulty understanding how to generate a pie chart. I have the following structure:

Segment  | Total
------------ | -------------
Home       | 520
Personal  | 1152

In the code I tried to do so:
```
echo Highcharts::widget([
                 'options' => [
                    'credits' => ['enabled' => false],
                    'title' => [
                        'text' => '',
                    ],
                    'plotOptions' => [
                        'pie' => [
                            'cursor' => 'pointer',
                        ],
                    ],
                    'series' => [
                        [
                          'type'=>'pie',                                                             
                          'name'=>'Elements',
                           'data' => [
                                [$seg, $total],
                          ],
                        ]
                    ],
                 ],
              ]);
```
But it did not work!
If I do a ```var_dump``` in the variables ```$sec``` and ```$total```, the result is this:

```array(2) { [0]=> string(4) "Home" [1]=> string(8) "Personal" }```

```array(2) { [0]=> int(55134) [1]=> int(116962) } ```

can you help me?

**Comment by gugoan** [comment]
Someone To Help ?

**Comment by miloschuman** [comment]
@gugoan, Check the format of your data against [Highcharts' Pie Chart Demos](http://www.highcharts.com/demo/pie-basic). Here is what your data should look like:

```php
// notice the keys 'name' and 'y'
$data = [
    ['name' => 'Home', 'y' => 55134],
    ['name' => 'Personal', 'y' => 116962]
];
echo Highcharts::widget([
    'options' => [
        'credits' => ['enabled' => false],
        'title' => [
            'text' => '',
        ],
        'plotOptions' => [
            'pie' => [
                'cursor' => 'pointer',
            ],
        ],
        'series' => [
            [
                'type' => 'pie',
                'name' => 'Elements',
                'data' => $data,
            ]
        ],
    ],
]);
```

**Comment by desarrollostello** [comment]
I have a similar problem, the question is that if I put the chart data is displayed correctly , but if you put the variable display is not correct. Then I show the two cases

`
$sql_loc = "select l.localidad, count(p.id) AS cantidad FROM proyecto p, localidad l WHERE p.idLocalidad = l.id GROUP BY p.idLocalidad ORDER BY cantidad";
		$raw_loc = $base = Yii::$app->db->createCommand($sql_loc)->queryAll();
    
		foreach ($raw_loc as $loc){
			$nombre_loc= $loc['localidad'];
			$cantidad_loc = $loc['cantidad'];
			$data_loc[] = [$nombre_loc,$cantidad_loc*1];
		}
		$data_loc = json_encode($data_loc);

```
echo Highcharts::widget([
				'scripts' => [
					'modules/exporting',
				],
			   'options' => [
					'chart' => 
					[
						'type' => 'pie',
					],
					'title' => ['text' => 'Proyectos por Localidad'],
					'legend' => ['enabled' => TRUE],
					'series' => [[                            // mind the [[ instead of [
						'type'=>'pie',
						'name'=>'Proyectos/Localidad',
						'data'=>$data_loc,
					]],
			   ]
			]);
```
`

In the above way does not work, but if I do a "echo " of the variable get this result

`
$data_loc = [["Catriel",1],["Ing. Huergo",1],["Sierra Grande",1],["Chimpay",1],["San Javier",1],["Valle Azul",1],["Cinco Saltos",1],["Gral. Fernandez Oro",2],["Cervantes",2],["Guardia Mitre",2],["Belisle",2],["Las Grutas",3],["Mainque9",3],["Darwin",3],["Campo Grande",3],["General Conesa",5],["Luis Beltran",6],["Valcheta",6],["Lamarque",7],["Pomona",7],["Allen",8],["Choele Choel",8],["El Bolson",10],["San Antonio Oeste",12],["Rio Colorado",17],["Cipolletti",21],["General Roca",21],["Villa Regina",30],["Viedma",49],["San Carlos de Bariloche",56]];
`
and if I put that $data instead of the graphic displayed correctly.

I could not find the error, can you help me please

`
echo Highcharts::widget([
				'scripts' => [
					'modules/exporting',
				],
			   'options' => [
					'chart' => 
					[
						'type' => 'pie',
					],
					'title' => ['text' => 'Proyectos por Localidad'],
					'legend' => ['enabled' => TRUE],
					'series' => [[                            // mind the [[ instead of [
						'type'=>'pie',
						'name'=>'Proyectos/Localidad',
						'data'=>[["Catriel",1],["Ing. Huergo",1],["Sierra Grande",1],["Chimpay",1],["San Javier",1],["Valle Azul",1],["Cinco Saltos",1],["Gral. Fernandez Oro",2],["Cervantes",2],["Guardia Mitre",2],["Belisle",2],["Las Grutas",3],["Mainque9",3],["Darwin",3],["Campo Grande",3],["General Conesa",5],["Luis Beltran",6],["Valcheta",6],["Lamarque",7],["Pomona",7],["Allen",8],["Choele Choel",8],["El Bolson",10],["San Antonio Oeste",12],["Rio Colorado",17],["Cipolletti",21],["General Roca",21],["Villa Regina",30],["Viedma",49],["San Carlos de Bariloche",56]],
					]],
			   ]
			]);
`
In this way it is displayed correctly
